# Disable the inherited requires
require: []

# Specify plugins explicitly
plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

# Inherit rules but override the loading mechanism
inherit_gem:
  rubocop-rails-omakase: rubocop.yml
